[AzCopyV10] Make piping more efficient with concurrency
Azure/azure-storage-azcopy pull request #1459
Opened 2021-05-28 03:14 UTC by siminsavani-msft

- Made piping efficient and configurable for download & upload.
- For **Upload**: extracted concurrencyValue from environment variable AZCOPY_CONCURRENCY_VALUE and replaced pipingUploadParallelism with this value. 
- For Download: extracted concurrencyValue from environment variable AZCOPY_CONCURRENCY_VALUE and utilized the high-level DoBatchTransfer function from Azure Go SDK (this code imitates logic in DownloadBlobToFile function).

2021-05-28 03:29 UTC, mohsha-msft commented
Hey @siminsavani-msft 

Did you try transferring large file through pipe upload/download?
If yes what were the perf improvements from before?

2021-05-28 05:20 UTC, siminsavani-msft commented
> Hey @siminsavani-msft
> 
> Did you try transferring large file through pipe upload/download?
> If yes what were the perf improvements from before?

Here are the results from perf testing:

_Format: (size, concurrency value, new/old code, upload/download): minute:seconds_

Test 1 (200 MB file, CV = 1, new, upload ): 3:07

Test 2 (200 MB file, CV=3, new, upload): 1:39

Test 3 (200 MB file, CV=1, new, download): 3:20 

Test 4 (200 MB file, CV=3, new, download): 1:01

Test 5 (200 MB file, CV=0, old, upload): 3:21

Test 6 (200 MB file, CV=0, old, download): 1:02

2021-05-28 06:07 UTC, mohsha-msft approved these changes
LGTM. Just try once by removing `AZCOPY_CONCURRENCY_VALUE` from environment variables to see the default behavior.

2021-06-02 07:35 UTC, zezha-msft requested changes

2021-06-02 07:35 UTC, zezha-msft commented on cmd/copy.go
> +				_, err = io.Copy(os.Stdout, body)
Wait, I don't think this is going to work. If each chunk is just writing to the Stdout whenever they are done, doesn't that corrupt the file content?

2021-06-02 07:40 UTC, zezha-msft requested changes

2021-06-02 07:40 UTC, zezha-msft commented on cmd/copy.go
> +				_, err = io.Copy(os.Stdout, body)
I think we need a synchronized writer, to write all the chunks out serially (they can be downloaded in parallel).

2021-06-02 07:50 UTC, mohsha-msft commented
Let's merge this in next release may be.

2021-06-25 05:48 UTC, siminsavani-msft commented
Here are the new perf results: https://microsoft-my.sharepoint.com/:x:/p/siminsavani/EQPBpJOeHb5AvCYHHzJIxcUBn4-t4Qt0UAIC_4BMq1nOhw?e=0fUC62

2021-08-12 22:31 UTC, adreed-msft requested changes

2021-08-12 22:31 UTC, adreed-msft commented on cmd/copy.go
> +				err = dstWriter.EnqueueChunk(ctx, common.ChunkID{}, cca.blockSize, os.Stdout, true)
Chunk IDs are not unused in the chunked file writer, and this kinda ignores the whole point of using the chunked file writer.

Leaving this empty is incorrect and will cause data corruption. Please look at the ChunkID struct, and properly fill it out as much as is feasible here.

2021-08-12 22:31 UTC, adreed-msft commented on cmd/copy.go
> +				_, err = dstWriter.Flush(ctx)
Flush should not be done until after the batch transfer has completed.

2022-01-05 22:45 UTC, adreed-msft approved these changes
Otherwise looks good.

2022-02-09 23:15 UTC, zezha-msft commented
Need perf test results for merging.

2023-12-11 20:40 UTC, closed without merging