MinIO TraceOn in DEBUG mode
Azure/azure-storage-azcopy pull request #1678
Opened 2022-02-22 11:03 UTC by mohsha-msft

2022-03-02 06:59 UTC, zezha-msft approved these changes
Please confirm that the necessary scrubbing is done when logging the trace.

2022-03-02 06:59 UTC, zezha-msft commented on cmd/zc_traverser_s3.go
> +				ste.JobsAdmin.LogToJobLog(strings.ReplaceAll(traceLog, "\n\n", "\n"), t.logLevel)
anything to scrub?

2022-03-04 06:34 UTC, nakulkar-msft requested changes
Inheriting logLevel from traverser or jptm is not necessary as we are always logging at pipeline.LogDebug. Consider defaulting logLevel in NewS3HTTPTraceLogger to pipeline.LogDebug.

2022-03-04 06:34 UTC, nakulkar-msft commented on cmd/zc_traverser_s3.go
> +	if t.logLevel == pipeline.LogDebug {
azcopyScanningLogger knows what level to log on, logLevel should need not be inherited from s3Client

2022-03-04 06:34 UTC, nakulkar-msft commented on ste/sourceInfoProvider-S3.go
> +	if jptm.MinimumLevelToLevel() == pipeline.LogDebug {
Here as well. The appLogger which is part of jptm has enough context to filter logLevel, log level need not be inherited from jptm, you should just set pipeline.LogDebug as level in NewS3HTTPTraceLogger

2022-03-16 07:18 UTC, nakulkar-msft approved these changes

2022-03-16 08:38 UTC, merged