quiet-mode-tiverma
Azure/azure-storage-azcopy pull request #1754
Opened 2022-04-22 10:12 UTC by tiverma-msft

2022-04-22 10:22 UTC, tiverma-msft commented
problems with rebasing, will have to resolve that issue

2022-04-25 08:03 UTC, mohsha-msft requested changes
Pull changes from azcopy:dev and rebase again. These commits shouldn't be part of the PR.

2022-04-27 15:41 UTC, tiverma-msft commented on cmd/copy.go
> +	// TODO if we press ctrl c, terminate without seeking answer whether user wants to quit
does it really ask if we wanna quit? doesn't it just end?

2022-05-04 05:17 UTC, nakulkar-msft commented on cmd/copy.go
> +	quietMode string
root.go would be a better place for this flag.

2022-05-04 05:17 UTC, nakulkar-msft commented on common/lifecyleMgr.go
> +	SetQuietMode(mode QuietMode) //TODO add this to all the commands
All the commands can inherit from root cmd.

2022-05-10 06:41 UTC, closed without merging