Azcopy sync option for file share is not supported
Azure/azure-storage-azcopy pull request #2666
Opened 2024-05-02 11:08 UTC by dphulkar-msft

**Issue Link:** https://github.com/Azure/azure-storage-azcopy/issues/2650

**Issue:**
The customer found the data loss issues when they used "Azcopy sync" to sync their on-premises files (millions of files) to Azure files. They detected few thousands of files are corrupted. 
Azcopy sync operation is not supported and is already documented [here](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-files#synchronize-files) 

**Resolution:**
Added a warning message which will be displayed on the console and in the job logs as well if the user tries to perform sync operation for file share.

**Console Output:**
![Screenshot 2024-05-02 163228](https://github.com/Azure/azure-storage-azcopy/assets/166800991/4aa1ab63-98db-461e-b8a8-b9c4179346b7)

**Job Log Output:**
[32b9249b-c4d7-9947-4352-1d7011f7eba9.log](https://github.com/Azure/azure-storage-azcopy/files/15187272/32b9249b-c4d7-9947-4352-1d7011f7eba9.log)

2024-05-03 05:07 UTC, dphulkar-msft commented on cmd/zt_sync_local_blob_test.go
> +// TestSyncGenerateWarningForLocalToFSUpload
sure. Should I create a new test file for this or do you want me to add to any existing test file? If existing, can you point me to the appropriate test file?

2024-05-06 20:46 UTC, pranavmalik-msft requested changes
Have we disabled the E2E test-cases? I can observe that they are not running in your case.

2024-05-07 21:59 UTC, adreed-msft commented
> Have we disabled the E2E test-cases? I can observe that they are not running in your case.

Seems to be caused by not originating from within the repo.

2024-05-10 18:16 UTC, gapra-msft commented
Closing this PR as this is a duplicate

2024-05-10 18:16 UTC, closed without merging